spring:
  application:
    name: fruit-mall-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19980708
    url: jdbc:mysql://8.129.87.61:3306/fruit_mall?useUniCode=true?charsetEncoding=utf-8?serverTimeZone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
  #  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: xhlong9798
#    url: jdbc:mysql://8.129.87.61:3306/fruit_mall?useUniCode=true?charsetEncoding=utf-8?serverTimeZone=GMT%2B8
#    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 8.129.87.61
    password: xhlong9798
    port: 6379
    database: 6
    timeout: 10000
  rabbitmq:
    host: 8.129.87.61
    port: 5672
    username: hl
    password: xhlong9798
    virtual-host: /fruit-mall
    publisher-confirm-type: correlated
    listener:
      direct:
        acknowledge-mode: manual
        prefetch: 1
    publisher-returns: true

server:
  servlet:
    context-path: /fruit-mall
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hl.fruitmall.entity.bean
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hl.fruitmallserver.mapper: debug


aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKeyId: LTAI4GKsWJN9WWFyyRS65WZr
    accessKeySecret: OKeEZQKU0TYt3noOkR7hjlFRjAYWXT
    bucketName: hl-fruit-mall
  sms:
    key-id: LTAI4GKsWJN9WWFyyRS65WZr
    key-secret: OKeEZQKU0TYt3noOkR7hjlFRjAYWXT
    sign-name: CcShare
    template-code: SMS_170181193